### ISSUE TITLE
AttributeError when “disconnecting” with Ctrl-C

### ISSUE THREAD

**Issue by gergelypolonkai** [shmup/miniboa#12]
I just copied the example to a `.py` file, connected using Linux `telnet`, and interrupted the connection with <kbd>Ctrl-C</kbd> within telnet. The server crashed with this traceback:

    Traceback (most recent call last):
      File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/home/polesz/Projects/c/wmud/wmud/__main__.py", line 28, in <module>
        server.poll()
      File "/home/polesz/Projects/c/wmud/.venv/lib64/python3.6/site-packages/miniboa/async.py", line 179, in poll
        self.clients[sock_fileno].socket_recv()
      File "/home/polesz/Projects/c/wmud/.venv/lib64/python3.6/site-packages/miniboa/telnet.py", line 309, in socket_recv
        self._iac_sniffer(byte)
      File "/home/polesz/Projects/c/wmud/.venv/lib64/python3.6/site-packages/miniboa/telnet.py", line 385, in _iac_sniffer
        self._three_byte_cmd(byte)
      File "/home/polesz/Projects/c/wmud/.venv/lib64/python3.6/site-packages/miniboa/telnet.py", line 484, in _three_byte_cmd
        self._note_local_option(option, False)
    AttributeError: 'TelnetClient' object has no attribute '_note_local_option'

Using Python 3.6.1 on Fedora 26, miniboa 1.0.0 is installed through pip.

**Comment by gergelypolonkai** [comment]
Bug doesn’t appear when installing miniboa from `master`

**Comment by shmup** [comment]
Ah, thanks for pointing that out.

**Comment by JASchilz** [comment]
I believe I've fixed this by deploying master to PyPi, now under version 1.0.2.

Unsure why pip was pulling down version 1.0.0 despite the fact that PyPi had a version 1.0.1. But after deploying master as 1.0.2, `pip install miniboa` now pulls down 1.0.2, which closes #12.
